apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "payment.fullname" . }}
  labels:
    {{- include "payment.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "payment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "payment.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  key: backend_host
                  name: {{ include "payment.fullname" . }}-common
            - name: FRONTEND_HOST
              valueFrom:
                configMapKeyRef:
                  key: frontend_host
                  name: {{ include "payment.fullname" . }}-common
            - name: ORIGINALS_HOST
              valueFrom:
                configMapKeyRef:
                  key: originals_host
                  name: {{ include "payment.fullname" . }}-common
            - name: ETHERS_NETWORK
              valueFrom:
                configMapKeyRef:
                  key: ethereum_network
                  name: {{ include "payment.fullname" . }}-common
            - name: RAPID_CRAWLING_COLLECTION_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingCollectionQueueName
                  name: {{ include "payment.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_COLLECTION_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingCollectionQueueUrl
                  name: {{ include "payment.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_ITEM_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingItemQueueName
                  name: {{ include "payment.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_ITEM_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingItemQueueUrl
                  name: {{ include "payment.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_REFRESH_ITEM_META_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingRefreshItemMetaQueueName
                  name: {{ include "payment.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_REFRESH_ITEM_META_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingRefreshItemMetaQueueUrl
                  name: {{ include "payment.fullname" . }}-aws-queue
            - name: HECTO_HASH_SECRET
              valueFrom:
                secretKeyRef:
                  key: hash_secret
                  name: {{ include "payment.fullname" . }}-hecto
            - name: HECTO_MID
              valueFrom:
                secretKeyRef:
                  key: mid
                  name: {{ include "payment.fullname" . }}-hecto
            - name: HECTO_NET_PAY_CANCLE
              valueFrom:
                secretKeyRef:
                  key: net_pay_cancle
                  name: {{ include "payment.fullname" . }}-hecto
            - name: HECTO_PAYMENT_INFO
              valueFrom:
                secretKeyRef:
                  key: payment_info
                  name: {{ include "payment.fullname" . }}-hecto
            - name: HECTO_PAY_CANCLE
              valueFrom:
                secretKeyRef:
                  key: pay_cancle
                  name: {{ include "payment.fullname" . }}-hecto
            - name: HECTO_PAY_APPROVE
              valueFrom:
                secretKeyRef:
                  key: pay_approve
                  name: {{ include "payment.fullname" . }}-hecto
            - name: HECTO_TR_INFO
              valueFrom:
                secretKeyRef:
                  key: tr_info
                  name: {{ include "payment.fullname" . }}-hecto
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: {{ include "payment.fullname" . }}-database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ include "payment.fullname" . }}-database
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "payment.fullname" . }}-database
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: {{ include "payment.fullname" . }}-database
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: {{ include "payment.fullname" . }}-database
            - name: DB_ENGINE
              valueFrom:
                secretKeyRef:
                  key: engine
                  name: {{ include "payment.fullname" . }}-database
            - name: DB_POOL_SIZE
              valueFrom:
                secretKeyRef:
                  key: pool_size
                  name: {{ include "payment.fullname" . }}-database
            - name: ETHERS_ALCHEMY_KEY
              valueFrom:
                secretKeyRef:
                  key: api_key
                  name: {{ include "payment.fullname" . }}-alchemy
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: region
                  name: {{ include "payment.fullname" . }}-aws-credentials
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: access_key
                  name: {{ include "payment.fullname" . }}-aws-credentials
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret_key
                  name: {{ include "payment.fullname" . }}-aws-credentials
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}