# Default values for payment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 293315485843.dkr.ecr.ap-northeast-2.amazonaws.com/kkr/payment
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  backend:
    backend_host: ""
    frontend_host: ""
    originals_host: ""
    ethereum_network: ""
  oauth:
    client_id: "test"
    client_secret: "secret"
    token_introspect_url: "http://auth.test-seokjae/oauth/token/introspec"
  aws:
    queue:
      rapidCrawlingCollectionQueueName: ""
      rapidCrawlingCollectionQueueUrl: ""
      rapidCrawlingItemQueueName: ""
      rapidCrawlingItemQueueUrl: ""
      rapidCrawlingRefreshItemMetaQueueName: ""
      rapidCrawlingRefreshItemMetaQueueUrl: ""

secret:
  hecto:
    hash_secret: ""
    mid: ""
    net_pay_cancle: ""
    payment_info: ""
    pay_cancle: ""
    pay_approve: ""
    tr_info: ""
  database:
    host: ""
    engine: ""
    database: ""
    password: ""
    port: ""
    user: ""
  alchemy:
    api_key: ""
  aws:
    region: ""
    access_key: ""
    secret_key: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  backend:
    enabled: true
    className: kong
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    host: test-seokjae.croffle.me
    hosts:
      - host: test.com
      - host: example.com
    tls:
      - hosts:
          - test-seokjae.croffle.me
        secretName: test-seokjae.croffle.me

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
