apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth.fullname" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "auth.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AUTHLIB_INSECURE_TRANSPORT
              value: "1"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_ENGINE
              valueFrom:
                secretKeyRef:
                  key: engine
                  name: {{ include "auth.fullname" . }}-database
            - name: OAUTH2_TOKEN_EXPIRES_IN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: oauth2-token-expires-in-password
                  name: {{ include "auth.fullname" . }}-oauth
            - name: OAUTH2_REFRESH_TOKEN_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  key: oauth2-refresh-token-expires-in
                  name: {{ include "auth.fullname" . }}-oauth
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-key
                  name: {{ include "auth.fullname" . }}-oauth
            - name: RESET_PIN_JWT_EXP
              valueFrom:
                secretKeyRef:
                  key: reset-pin-jwt-exp
                  name: {{ include "auth.fullname" . }}-oauth
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: aws-region
                  name: {{ include "auth.fullname" . }}-aws
            - name: AWS_ACCESS_KEY
              valueFrom:
               secretKeyRef:
                  key: aws-access-key
                  name: {{ include "auth.fullname" . }}-aws
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: aws-secret-key
                  name: {{ include "auth.fullname" . }}-aws
            - name: NEW_ACCOUNT_REPORT_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: new-account-report-queue-url
                  name: {{ include "auth.fullname" . }}-aws
            - name: AWS_WALLET_CREATE_NOTIFICATION_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: wallet-create-notification-queue-name
                  name: {{ include "auth.fullname" . }}-aws
            - name: AWS_WALLET_CREATE_NOTIFICATION_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: wallet-create-notification-queue-url
                  name: {{ include "auth.fullname" . }}-aws
            - name: NONCE_TEMPLATE
              valueFrom:
                configMapKeyRef:
                  key: nonce-template
                  name: {{ include "auth.fullname" . }}-common
            - name: TOS_URL
              valueFrom:
                configMapKeyRef:
                  key: tos-url
                  name: {{ include "auth.fullname" . }}-common
            - name: TOS_UPDATED
              valueFrom:
                configMapKeyRef:
                  key: tos-updated
                  name: {{ include "auth.fullname" . }}-common
            - name: IDENTITY_DANAL_API_BASE
              valueFrom:
                configMapKeyRef:
                  key: identity-danal-api-base
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_DANAL_CPID
              valueFrom:
                secretKeyRef:
                  key: identity-danal-cpid
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_DANAL_CPPWD
              valueFrom:
                secretKeyRef:
                  key: identity-danal-cppwd
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_DANAL_TARGET_URL
              valueFrom:
                configMapKeyRef:
                  key: identity-danal-target-url
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_USER_DANAL_TARGET_URL
              valueFrom:
                configMapKeyRef:
                  key: identity-user-danal-target-url
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_RESET_PIN_DANAL_TARGET_URL
              valueFrom:
                configMapKeyRef:
                  key: identity-reset-pin-danal-target-url
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_VALID_REDIRECT_URLS
              valueFrom:
                secretKeyRef:
                  key: identity-valid-redirect-urls
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_OAUTH_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: identity-oauth-client-id
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                  key: identity-encrypt-key
                  name: {{ include "auth.fullname" . }}-identity
            - name: IDENTITY_HOME_PAGE
              valueFrom:
                configMapKeyRef:
                  key: identity-home-page
                  name: {{ include "auth.fullname" . }}-identity
            - name: SOCIAL_LOGIN_APPLE_APP_ID
              valueFrom:
                secretKeyRef:
                  key: social-login-apple-app-id
                  name: {{ include "auth.fullname" . }}-social
            - name: WALLET_BACKEND_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: wallet-backend-base-url
                  name: {{ include "auth.fullname" . }}-common
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
