{{- if .Values.ingress.enabled -}}
{{- $namespace := .Release.Namespace -}}
apiVersion: configuration.konghq.com/v1
config:
  origins:
  - '*'
kind: KongPlugin
metadata:
  name: {{ include "originals.cors" . }}
plugin: cors
---
apiVersion: configuration.konghq.com/v1
config:
  auth_method: client_secret_basic
  auth_response_headers_to_forward:
  - sub
  - current-address
  client_id: {{ default "" .Values.config.oauth.client_id | quote }}
  client_secret: {{ default "" .Values.config.oauth.client_secret | quote }}
  token_introspect_url: {{ default "" .Values.config.oauth.token_introspect_url | quote }}
kind: KongPlugin
metadata:
  name: {{ include "originals.validateAuthServerToken" . }}
plugin: oauth2-token-introspection-request
{{- end }}
