apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ETHEREUM_NETWORK
              valueFrom:
                configMapKeyRef:
                  key: ethreum_network
                  name: {{ include "backend.fullname" . }}-common
            - name: MARKETPLACE_NFT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: marketplace_nft_address
                  name: {{ include "backend.fullname" . }}-common
            - name: NETWORK_PROVIDER
              valueFrom:
                configMapKeyRef:
                  key: network_provider
                  name: {{ include "backend.fullname" . }}-common
            - name: ACCOUNT_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: account_api_base_url
                  name: {{ include "backend.fullname" . }}-common
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  key: chain_id
                  name: {{ include "backend.fullname" . }}-common
            - name: PAYMENT_HOST
              valueFrom:
                configMapKeyRef:
                  key: payment_host
                  name: {{ include "backend.fullname" . }}-common
            - name: ORIGINALS_HOST
              valueFrom:
                configMapKeyRef:
                  key: originals_host
                  name: {{ include "backend.fullname" . }}-common
            - name: MARKETPLACE_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: marketplace
                  name: {{ include "backend.fullname" . }}-contract
            - name: ALCHEMY_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: {{ include "backend.fullname" . }}-alchemy
            - name: ALCHEMY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api_key
                  name: {{ include "backend.fullname" . }}-alchemy
            - name: OPENSEA_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api_key
                  name: {{ include "backend.fullname" . }}-opensea
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: {{ include "backend.fullname" . }}-database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ include "backend.fullname" . }}-database
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "backend.fullname" . }}-database
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: {{ include "backend.fullname" . }}-database
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: {{ include "backend.fullname" . }}-database
            - name: DB_ENGINE
              valueFrom:
                secretKeyRef:
                  key: engine
                  name: {{ include "backend.fullname" . }}-database
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: region
                  name: {{ include "backend.fullname" . }}-aws-credentials
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: access_key
                  name: {{ include "backend.fullname" . }}-aws-credentials
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret_key
                  name: {{ include "backend.fullname" . }}-aws-credentials
            - name: WETH_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: weth
                  name: {{ include "backend.fullname" . }}-contract
            - name: USDC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: usdc
                  name: {{ include "backend.fullname" . }}-contract
            - name: COLLECTION_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: collectionQueueName
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: COLLECTION_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: collectionQueueUrl
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: REFRESH_ITEM_META_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: refreshItemMetaQueueName
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: REFRESH_ITEM_META_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: refreshItemMetaQueueUrl
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: ORDER_FILL_CHANGED_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: orderFillChangedQueueName
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: ORDER_FILL_CHANGED_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: orderFillChangedQueueUrl
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: ORDERS_MATCHED_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: ordersMatchedQueueName
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: ORDERS_MATCHED_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: ordersMatchedQueueUrl
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_COLLECTION_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingCollectionQueueName
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_COLLECTION_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingCollectionQueueUrl
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_ITEM_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingItemQueueName
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_ITEM_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingItemQueueUrl
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_REFRESH_ITEM_META_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingRefreshItemMetaQueueName
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: RAPID_CRAWLING_REFRESH_ITEM_META_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: rapidCrawlingRefreshItemMetaQueueUrl
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: S3_BUCKET_COLLECTION
              valueFrom:
                configMapKeyRef:
                  key: s3BucketCollection
                  name: {{ include "backend.fullname" . }}-aws-s3
            - name: S3_BUCKET_ITEM
              valueFrom:
                configMapKeyRef:
                  key: s3BucketItem
                  name: {{ include "backend.fullname" . }}-aws-s3
            - name: S3_KEY_MAIN_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: s3KeyMainImage
                  name: {{ include "backend.fullname" . }}-aws-s3
            - name: S3_KEY_BACKGROUND_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: s3KeyBackgroundImage
                  name: {{ include "backend.fullname" . }}-aws-s3
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
